let userName = prompt('Введите ваше имя:');
console.log('Меня зовут ' + userName);
let userAge = prompt('Введите свой возраст:');
console.log('Мне ' + userAge + ' лет');
let question1 = prompt('Решите пример 20 - 10 = ?');
let result1 = 20 - 10;
console.log('Пример = 20 - 10 ' + 'Мой ответ = ' + question1 + '. Правилный ответ = ' + result1);
let question2 = prompt('Решите пример 5 + 3 = ?');
let result2 = 5 + 3;
console.log('Пример = 5 + 3 ' + 'Мой ответ = ' + question2 + '. Правильный ответ = ' + result2);
let question3 = prompt('Решите пример 7 * 4 = ,');
let result3 = 7 * 4;
console.log('Пример = 7 * 4 ' + 'Мой ответ = ' + question3 + '. Правильный ответ = ' + result3);
let question4 = prompt('Решите пример 16 / 4 = ?');
let result4 = 16 / 4;
console.log('Пример = 16 / 4 ' + 'Мой ответ = ' + question4 + '. Правильный ответ = ' + result4);
alert('Откройте консоль разработчика');
X = prompt('Введите первое число');
Y = prompt('Введите второе число');
Z = prompt('Введите третье число');
res = X + Y + Z;
result = res/3;
console.log('Среднее число от ' + X + Y + Z + ' это ' + result);